railsApp/movieOverview/config/routes.rb
MovieOverview::Application.routes.draw do

	#only admin actions
  resources :menu_entries
  resources :groups
	resources :posts
	resources :generes
	
  get "/search", to: 'search#index' 
	get '' , to: 'sessions#home' 
	get '/logout', to: 'sessions#logout' 	
	get '/home', to: 'sessions#home' 
	get '/profile', to: 'sessions#profile' 
	get '/profile/:id', to: 'sessions#profile'
	get '/profile/:id/:menu', to: 'sessions#profile'
	get '/profile/:menu', to: 'sessions#profile'
	post '/profile/add_state', to: 'posts#create'
	get '/posts/get_next_posts/:uid/:offset', to: 'posts#getNextPosts'
	get '/m/:movie_id' , to: 'movies#show'
	post '/movies/new'

	match '/search', to: 'search#index', via: [:get, :post]
	match '/create', to: 'users#create', via: [:get, :post]
	match '/login', to: 'session#login', via: [:get, :post]
	
	#default route
	match ':controller/:action' , via: [:get, :post]
end

railsApp/movieOverview/app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
end

railsApp/movieOverview/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
	before_filter :authenticate_user 

  def index
    @groups = Group.all
  end

  def show
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'create' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :description, :user_id)
    end
end

railsApp/movieOverview/app/helpers/groups_helper.rb
module GroupsHelper
end

railsApp/movieOverview/app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsApp/movieOverview/app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

railsApp/movieOverview/app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= group.user %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

railsApp/movieOverview/app/views/groups/new.html.erb
<h1>Neue Gruppe</h1>

<%= form_tag "/groups/new", method: "post" do %>
	<div class="span10">
		<%= label_tag :name , "Name der Gruppe: " , class:"label label-inverse" %><br>
		<%= text_field_tag :name %><br/>
		<%= label_tag :des , "Beschreibung der Gruppe: " , class:"label label-inverse" %><br>
		<%= text_area_tag :des %><br/>
		<%= label_tag :permission , "Rechte der Gruppe: " , class:"label label-inverse" %><br>
	</div>
	<table id="permission" class="table table-hover span5" style="padding:30px; border: 2px solid grey; border-radius: 8px">
	<% session[:perms].each do |x| %>
	<tr>
		<td class="span4"><%= label_tag x[0] , x[1] %></td>
		<td><%= check_box_tag x[0] , "permission[#{x[0]}]" %></td>
	<tr>
	<% end %>
	</table>
	<%= submit_tag "Erstellen" , class: "btn btn-success btn-large" %>
<% end %>

railsApp/movieOverview/app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @group.user %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>