railsApp/movieOverview/config/routes.rb
MovieOverview::Application.routes.draw do

	#only admin actions
  resources :menu_entries
  resources :groups
	resources :posts
	resources :generes
	
  get "/search", to: 'search#index' 
	get '' , to: 'sessions#home' 
	get '/logout', to: 'sessions#logout' 	
	get '/home', to: 'sessions#home' 
	get '/profile', to: 'sessions#profile' 
	get '/profile/:id', to: 'sessions#profile'
	get '/profile/:id/:menu', to: 'sessions#profile'
	get '/profile/:menu', to: 'sessions#profile'
	post '/profile/add_state', to: 'posts#create'
	get '/posts/get_next_posts/:uid/:offset', to: 'posts#getNextPosts'
	get '/m/:movie_id' , to: 'movies#show'
	post '/movies/new'

	match '/search', to: 'search#index', via: [:get, :post]
	match '/create', to: 'users#create', via: [:get, :post]
	match '/login', to: 'session#login', via: [:get, :post]
	
	#default route
	match ':controller/:action' , via: [:get, :post]
end

railsApp/movieOverview/app/controllers/menu_entries_controller.rb
class MenuEntriesController < ApplicationController

	before_filter :authenticate_user
  before_action :set_menu_entry, only: [:show, :edit, :update, :destroy]

  # GET /menu_entries
  # GET /menu_entries.json
  def index
    @menu_entries = MenuEntrie.all
  end

  # GET /menu_entries/1
  # GET /menu_entries/1.json
  def show
  end

  # GET /menu_entries/new
  def new
    @menu_entry = MenuEntrie.new
  end

  # GET /menu_entries/1/edit
  def edit
  end

  # POST /menu_entries
  # POST /menu_entries.json
  def create
    @menu_entry = MenuEntrie.new(menu_entry_params)

    respond_to do |format|
      if @menu_entry.save
        format.html { redirect_to @menu_entry, notice: 'Menu entrie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @menu_entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @menu_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_entries/1
  # PATCH/PUT /menu_entries/1.json
  def update
    respond_to do |format|
      if @menu_entry.update(menu_entry_params)
        format.html { redirect_to @menu_entry, notice: 'Menu entrie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @menu_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_entries/1
  # DELETE /menu_entries/1.json
  def destroy
    @menu_entry.destroy
    respond_to do |format|
      format.html { redirect_to menu_entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_entry
      @menu_entry = MenuEntrie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_entry_params
      params.require(:menu_entrie).permit(:title)
    end
end

railsApp/movieOverview/app/helpers/menu_entries_helper.rb
module MenuEntriesHelper
end

railsApp/movieOverview/app/views/menu_entries/_form.html.erb
<%= form_for(@menu_entry) do |f| %>
  <% if @menu_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_entry.errors.count, "error") %> prohibited this menu_entry from being saved:</h2>

      <ul>
      <% @menu_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsApp/movieOverview/app/views/menu_entries/edit.html.erb
<h1>Editing menu_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu_entry %> |
<%= link_to 'Back', menu_entries_path %>

railsApp/movieOverview/app/views/menu_entries/index.html.erb
<h1>Listing menu_entries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @menu_entries.each do |menu_entry| %>
      <tr>
        <td><%= menu_entry.title %></td>
        <td><%= link_to 'Show', menu_entry %></td>
        <td><%= link_to 'Edit', edit_menu_entry_path(menu_entry) %></td>
        <td><%= link_to 'Destroy', menu_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu entrie', new_menu_entry_path %>

railsApp/movieOverview/app/views/menu_entries/new.html.erb
<h1>New menu_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', menu_entries_path %>

railsApp/movieOverview/app/views/menu_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @menu_entry.title %>
</p>

<%= link_to 'Edit', edit_menu_entry_path(@menu_entry) %> |
<%= link_to 'Back', menu_entries_path %>