railsApp/movieOverview/config/routes.rb
MovieOverview::Application.routes.draw do

	#only admin actions
  resources :menu_entries
  resources :groups
	resources :posts
	resources :generes
	
  get "/search", to: 'search#index' 
	get '' , to: 'sessions#home' 
	get '/logout', to: 'sessions#logout' 	
	get '/home', to: 'sessions#home' 
	get '/profile', to: 'sessions#profile' 
	get '/profile/:id', to: 'sessions#profile'
	get '/profile/:id/:menu', to: 'sessions#profile'
	get '/profile/:menu', to: 'sessions#profile'
	post '/profile/add_state', to: 'posts#create'
	get '/posts/get_next_posts/:uid/:offset', to: 'posts#getNextPosts'
	get '/m/:movie_id' , to: 'movies#show'
	post '/movies/new'

	match '/search', to: 'search#index', via: [:get, :post]
	match '/create', to: 'users#create', via: [:get, :post]
	match '/login', to: 'session#login', via: [:get, :post]
	
	#default route
	match ':controller/:action' , via: [:get, :post]
end

railsApp/movieOverview/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	before_filter :authenticate_user, :only => :new

  def new
		if request.post?
			genere = Genere.find_by_title(params[:genere]).id
			unless genere.nil?
				moviename = params[:moviename]
				@movie = Movie.new
				@movie.name = moviename
				# @movie.rating will be set automatically via trigger
				@movie.genere = genere
				@movie.description = moviename
				if @movie.save
					flash[:success] = "Film wurde erstellt."
					redirect_to :action => :show, :movie_id => moviename
				else
					begin
						unless Movie.find_by_name(moviename).nil?
          		flash[:success] = "Film wurde gefunden."
          		redirect_to :action => :show , :movie_id => moviename
						end	
					rescue => e 
							flash[:error] = "Film konnte nicht angelegt werden, bitte Filmname prüfen"+e.message
					end
				end
			else
				flash[:error] = "Genere konnte nicht gefunden werden"
			end
		end
  end

  def show                                                                                                   
    if movie=params[:movie_id]
      @movie = Movie.find_by_name(movie) unless movie.is_num?
			@movie = Movie.find(movie) if movie.is_num?
			begin
				@media = @movie.media_resources
				if @media.empty?
					trailer = Movie.getTrailerURL(@movie.name)
					images = Movie.getAryImages(@movie.name)
					flash[:info] = trailer
					if !trailer.nil? || !images.nil?
						add = MediaResource.new
						add.typ_id = GA_VIDEO
						add.src = trailer
						add.movie_id = @movie.id
						(add.save) ? (debug = "Trailer hinzugefügt") : (debug = "Fehler beim hinzufügen des Trailers")
						(images.length).times do |x| 
							add = MediaResource.new
							add.typ_id = GA_IMAGE
							add.src = images[x]
							add.movie_id = @movie.id
							(add.save) ? (debug += "<br>Bild ##{x} hinzugefügt") : (debug += "<br>Fehler beim hinzufügen des Bildes ##{x}")
						end
					end
				end
			rescue => e
        flash[:error] = "Es ist ein Fehler aufgetreten "+e.message
        redirect_to :home
      end 
		end                                                                                                                                       
  end
 

	def rate(data = [])
		if request.post? || !data
			user_id = session[:user_id]
			if data
				movie_id = params[:movie_id] 
				rating = params[:star]
			else
				movie_id = data[0]
				rating = data[1]
			end
			out="#{movie_id} - #{rating}" 
			if Rating.isDuplicate?(user_id, movie_id)
				id = Rating.find_id_by_user_and_movie(user_id,movie_id)
				@record = Rating.find(id)
				@record.value = rating
				(@record.save) ? (flash[:success] = "Rating wurde erfolgreich angpasst") : (flash[:error] = "Bearbeitungsfehler beim Rating anpassen"+out)
				redirect_to :back				
			else
				@record = Rating.new
				@record.movie_id = movie_id
				@record.user_id = user_id
				@record.value = rating
				(@record.save) ? (flash[:success] = "Rating wurde erfolgreich gesetzt") : (flash[:error] = "Bearbeitungsfehler beim Rating erstellen"+out)
				redirect_to :back
			end
		end
	end

	private

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :description, :rating, :genere)
    end
end

class String
  def is_num?
    true if Float(self) rescue false
  end
end

railsApp/movieOverview/app/helpers/movies_helper.rb
module MoviesHelper
end

railsApp/movieOverview/app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :genere %><br>
    <%= f.number_field :genere %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsApp/movieOverview/app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

railsApp/movieOverview/app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Genere</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.description %></td>
        <td><%= movie.rating %></td>
        <td><%= movie.genere %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

railsApp/movieOverview/app/views/movies/new.html.erb
<h1>Neuen Film hinzufügen</h1>

<%= form_tag "/movies/new"  do %>
	<div class="span12"><%= label_tag :moviename , "Bitte so deklarieren: 'MeinNeuerFilm_Episode3' 
													--- Achtung --- Es werden keine weiteren Sonderzeichen akzeptiert (ä,ö,...)", 
													class: "label label-important"%></div>
	<div class="span12"><%= text_field_tag :moviename , nil , :placeholder => "Hier einen Namen eingeben" , :class => "span3" , :autocomplete => "off"%> </div>
	<div class="span12"></div>
	<div class="span12">
		<div class="span2"><%= label_tag :genere , "Genere:", class: "label label-inverse"%>  </div>
		<%= select_tag(:genere, options_for_select(Genere.all.map(&:title))) %></div> 
	<div class="span12">
		<div class="span2"><%= label_tag :description , "Beschreibung:", class: "label label-inverse"%>  </div>
		<%= text_area_tag :description %></div> 
	<div class="span12"><%= submit_tag "Erstellen" , :class => "btn btn-inverse btn-large"%></div> 
<% end %>

railsApp/movieOverview/app/views/movies/show.html.erb
<h2><%= @movie.name.gsub("_"," ") %></h2>

<!-- LOAD FROM GOOGLE -->
<% unless @media.empty? %>
<ul class="thumbnails">
	<% @media.each do |x| %>
		<%	if x.typ_id == GA_IMAGE	%>
			<li class="span3">
				<a class="thumbnail">
					<img src="<%= x.src %>" alt=""/>
				</a>
			</li>
		<% end %>
	<% end %>
</ul>
<% end %>
<!-- END -->

<table class="table table-hover">
	<% unless @movie.description.empty?  %>
	<tr>
	  <td class="span5"><h4>Beschreibung:</h4></div>
	  <td class="well"><%= @movie.description %></div>
	</tr>
	<% end %>
	<tr>
  	<td class="span5"><h4>Rating:
  	<span style="color: orangered"><%= @movie.rating %></span><h4></td>
		<td class="span7">
			<%= form_tag "/movies/rate" , id: "ratingform" do %>
			<%= hidden_field_tag :movie_id , @movie.id%>
				<% 5.times do |i|%>
					<input name="star" type="radio" value="<%= i+1 %>" class="star <%= "required" if i+1 == 1 %>" <%= "checked" if @movie.rating.to_i == i+1 %>/>
				<% end %>
			<%= submit_tag "Bewerten", style: "display:none"%>
			<% end %>
	</td>
	</tr>
	<tr>
  	<td class="span5"><h4>Genere:</h4></td>
  	<td class="span7"><span class="label label-inverse"><%= Genere.find(@movie.genere).title %></span></td>
	</tr>
	<% unless @media.empty?%>
	<tr>
		<td class="span5"><h4>Gefundenes Video:</h4></td>
		<td class="span7"><iframe width="560" height="315" 
			src="//www.youtube.com/embed/<%= @media.select{|x| x if x.typ_id == GA_VIDEO}.map(&:src).join.split("v=")[1].split("&")[0] %>" 
			frameborder="0" allowfullscreen></iframe></td>
	</tr>
	<% end %>
</table>

<script>
	$('.star').rating({
		callback: function(value, link){
			$( "#ratingform" ).submit();
		}
	});
</script>