railsApp/movieOverview/config/routes.rb
MovieOverview::Application.routes.draw do

	#only admin actions
  resources :menu_entries
  resources :groups
	resources :posts
	resources :generes
	
  get "/search", to: 'search#index' 
	get '' , to: 'sessions#home' 
	get '/logout', to: 'sessions#logout' 	
	get '/home', to: 'sessions#home' 
	get '/profile', to: 'sessions#profile' 
	get '/profile/:id', to: 'sessions#profile'
	get '/profile/:id/:menu', to: 'sessions#profile'
	get '/profile/:menu', to: 'sessions#profile'
	post '/profile/add_state', to: 'posts#create'
	get '/posts/get_next_posts/:uid/:offset', to: 'posts#getNextPosts'
	get '/m/:movie_id' , to: 'movies#show'
	post '/movies/new'

	match '/search', to: 'search#index', via: [:get, :post]
	match '/create', to: 'users#create', via: [:get, :post]
	match '/login', to: 'session#login', via: [:get, :post]
	
	#default route
	match ':controller/:action' , via: [:get, :post]
end

railsApp/movieOverview/app/models/genere.rb
class Genere < ActiveRecord::Base
end

railsApp/movieOverview/app/controllers/generes_controller.rb
class GeneresController < ApplicationController
  before_action :set_genere, only: [:show, :edit, :update, :destroy]

  # GET /generes
  # GET /generes.json
  def index
    @generes = Genere.all
  end

  # GET /generes/1
  # GET /generes/1.json
  def show
  end

  # GET /generes/new
  def new
    @genere = Genere.new
  end

  # GET /generes/1/edit
  def edit
  end

  # POST /generes
  # POST /generes.json
  def create
    @genere = Genere.new(genere_params)

    respond_to do |format|
      if @genere.save
        format.html { redirect_to @genere, notice: 'Genere was successfully created.' }
        format.json { render action: 'show', status: :created, location: @genere }
      else
        format.html { render action: 'new' }
        format.json { render json: @genere.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generes/1
  # PATCH/PUT /generes/1.json
  def update
    respond_to do |format|
      if @genere.update(genere_params)
        format.html { redirect_to @genere, notice: 'Genere was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @genere.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generes/1
  # DELETE /generes/1.json
  def destroy
    @genere.destroy
    respond_to do |format|
      format.html { redirect_to generes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genere
      @genere = Genere.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genere_params
      params.require(:genere).permit(:title)
    end
end

railsApp/movieOverview/app/helpers/generes_helper.rb
module GeneresHelper
end

railsApp/movieOverview/app/views/generes/_form.html.erb
<%= form_for(@genere) do |f| %>
  <% if @genere.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genere.errors.count, "error") %> prohibited this genere from being saved:</h2>

      <ul>
      <% @genere.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsApp/movieOverview/app/views/generes/edit.html.erb
<h1>Editing genere</h1>

<%= render 'form' %>

<%= link_to 'Show', @genere %> |
<%= link_to 'Back', generes_path %>

railsApp/movieOverview/app/views/generes/index.html.erb
<h1>Listing generes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @generes.each do |genere| %>
      <tr>
        <td><%= genere.title %></td>
        <td><%= link_to 'Show', genere %></td>
        <td><%= link_to 'Edit', edit_genere_path(genere) %></td>
        <td><%= link_to 'Destroy', genere, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Genere', new_genere_path %>

railsApp/movieOverview/app/views/generes/new.html.erb
<h1>New genere</h1>

<%= render 'form' %>

<%= link_to 'Back', generes_path %>

railsApp/movieOverview/app/views/generes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @genere.title %>
</p>

<%= link_to 'Edit', edit_genere_path(@genere) %> |
<%= link_to 'Back', generes_path %>